### ISSUE TITLE
Add an option to disable the query stream deserialize

### ISSUE THREAD

**Issue by gadi-ray** [vweevers/lento#27]
@vweevers I don't need to convert the dates to Date object, can we add an option to skip the deserialization? I can open a PR

**Comment by vweevers** [comment]
Sure, PR is welcome!

**Comment by gadi-ray** [comment]
Cool! can you please give me permissions?

**Comment by vweevers** [comment]
You don't need permissions. Fork the repo to your account and make changes there, then open a PR.

**Comment by vweevers** [comment]
If it's your first time, this may help: https://opensource.com/article/19/7/create-pull-request-github

**Comment by vweevers** [comment]
#28
