### ISSUE TITLE
Handle 204 code?

### ISSUE THREAD

**Issue by vweevers** [vweevers/lento#4]
It's not in the docs but I came across this: 

https://github.com/prestodb/presto/blob/61ff7d087b2cd4679df00e6a0fda5856d8d61ab0/presto-main/src/main/java/com/facebook/presto/operator/HttpPageBufferClient.java#L530

**Comment by vweevers** [comment]
I haven't seen a 204, running queries every hour for about a year, but I guess it depends on the type of query. If you do encounter a 204, LMK and I'll reopen this.

**Comment by findepi** [comment]
Presto uses "204 No Content" for internal communication. It currently does not use 204 in client protocol.
